name: Test LinkChecker

on:
  workflow_dispatch:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run LinkChecker
        id: self-check
        uses: ./
        with:
          files: test.md
          blacklist:  https://www.github.com/paramt/this-doesnt-exist
